name: ResSlots
main: to.joe.j2mc.resslots.J2MC_ReservedSlots
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Reserved slots module
permissions:
  j2mc.resslots.resslot:
    description: res slot holder
